<!DOCTYPE html>
<html>
    <head>
        <title>Technical Documents(English) : 3. Altibase Trace Logs</title>
        <link rel="stylesheet" href="styles/site.css" type="text/css" />
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>

    <body class="theme-default aui-theme-default">
        <div id="page">
            <div id="main" class="aui-page-panel">
                <div id="main-header">
                    <div id="breadcrumb-section">
                        <ol id="breadcrumbs">
                            <li class="first">
                                <span><a href="index.html">Technical Documents(English)</a></span>
                            </li>
                                                    <li>
                                <span><a href="Home_557064.html">Home</a></span>
                            </li>
                                                    <li>
                                <span><a href="Altibase-Development-Guide_14058519.html">Altibase Development Guide</a></span>
                            </li>
                                                </ol>
                    </div>
                    <h1 id="title-heading" class="pagetitle">
                                                <span id="title-text">
                            Technical Documents(English) : 3. Altibase Trace Logs
                        </span>
                    </h1>
                </div>

                <div id="content" class="view">
                    <div class="page-metadata">
                        
        
    
        
    
        
    
            Created by <span class='author'> richard.nahm	</span>, last modified on Feb 18, 2021
                        </div>
                    <div id="main-content" class="wiki-content group">
                    <p><style type='text/css'>/*<![CDATA[*/
div.rbtoc1624409360222 {padding: 0px;}
div.rbtoc1624409360222 ul {list-style: disc;margin-left: 0px;}
div.rbtoc1624409360222 li {margin-left: 0px;padding-left: 0px;}

/*]]>*/</style><div class='toc-macro rbtoc1624409360222'>
<ul class='toc-indentation'>
<li><a href='#id-3.AltibaseTraceLogs-Classificationoftracelogs'>Classification of trace logs</a>
<ul class='toc-indentation'>
<li><a href='#id-3.AltibaseTraceLogs-altibase_sm.log'>altibase_sm.log</a></li>
<li><a href='#id-3.AltibaseTraceLogs-altibase_qp.log'>altibase_qp.log</a></li>
<li><a href='#id-3.AltibaseTraceLogs-altibase_rp.log'>altibase_rp.log</a></li>
<li><a href='#id-3.AltibaseTraceLogs-altibase_dk.log'>altibase_dk.log</a></li>
<li><a href='#id-3.AltibaseTraceLogs-altibase_error.log'>altibase_error.log</a></li>
</ul>
</li>
</ul>
</div></p><hr /><p>ALTIBASE records trace logs for important status information and errors for each module in the $ALTIBASE_HOME/trc path, which is the installed path. </p><h2 id="id-3.AltibaseTraceLogs-Classificationoftracelogs"><strong>Classification of trace logs</strong></h2><p>The trace log recorded by ALTIBASE is as follows.</p><div class="table-wrap"><table class="confluenceTable"><thead><tr><th class="confluenceTh"><div class="tablesorter-header-inner"><p>Classification</p></div></th><th class="confluenceTh"><div class="tablesorter-header-inner"><p>Description</p></div></th></tr></thead><tbody><tr><td class="confluenceTd"><p>altibase_boot.log</p></td><td class="confluenceTd">Records start/stop the process and overall DBMS log<p> </p></td></tr><tr><td class="confluenceTd"><p>altibase_sm.log</p></td><td class="confluenceTd"><p>Records logs related to checkpoints and tablespaces</p></td></tr><tr><td class="confluenceTd"><p>altibase_qp.log</p></td><td class="confluenceTd"><p>Records logs related to DDL execution and query processing</p></td></tr><tr><td class="confluenceTd"><p>altibase_rp.log</p></td><td class="confluenceTd"><p>Records logs related to replication</p></td></tr><tr><td class="confluenceTd"><p>altibase_dk.log</p></td><td class="confluenceTd">Records logs related to DB Link<p> </p></td></tr><tr><td class="confluenceTd"><p>altibase_xa.log</p></td><td class="confluenceTd"><p>Records logs related to XA transaction</p></td></tr><tr><td class="confluenceTd"><p>altibase_mm.log</p></td><td class="confluenceTd">Records logs created when processing the main module<p> </p></td></tr><tr><td class="confluenceTd"><p>altibase_error.log</p></td><td class="confluenceTd"><p>Records logs related to errors occurring on the server</p></td></tr><tr><td class="confluenceTd"><p>altibase_dump.log</p></td><td class="confluenceTd"><p>Records debugging logs for errors occurring on the server.</p></td></tr></tbody></table></div><p>By default, the log files are circulated to altibase_xx.log-[1-10], including altibase_xx.log, to record 10 log files.</p><p>In the following, messages that are meaningful to the user are explained separately for each trace log.</p><p><strong>altibase_boot.log</strong></p><hr /><p><span style="color: orange;"><span style="color: rgb(0,51,102);">The user must check altibase_boot.log first when an error occurs in DBMS.</span> The </span><span style="color: orange;">orange color <span style="color: rgb(0,51,102);"><span style="color: rgb(0,0,0);">mark in the table is an error that the user must resolve.</span></span></span></p><div class="table-wrap"><table class="confluenceTable"><thead><tr><th class="confluenceTh"><div class="tablesorter-header-inner"><p><span style="color: orange;">ERR-0108d (errno=0) License is invalid or expired.</span></p></div></th></tr></thead><tbody><tr><td class="confluenceTd"><p>This error occurs when the license file is missing or incorrect when starting up. The user must check the license information in ALTIBASE and have it reissued if necessary.</p></td></tr><tr><th class="confluenceTh"><p><span style="color: orange;">ERR-01052(errno=13) Unable to invoke open() function on [/dbs/mydb-0-0]</span></p></th></tr><tr><td class="confluenceTd"><p>This error occurs when the DB has not been created before the initial operation or when there is no permission to access the file. The user must create a DB or check if the user has permission to access directories and files. Alternatively, it may be the case that the data file was deleted by mistake by the user. In this case, a procedure to recover using a backup copy is required.</p></td></tr><tr><th class="confluenceTh"><p><span style="color: orange;">ERR-01052(errno=2) Unable to invoke open() function on [/dblog01/logfile536358]</span></p></th></tr><tr><td class="confluenceTd"><p>During the Altibase operation phase, automatic recovery is performed, which occurs when the redo log file required for this process is damaged or does not exist. The user must request technical support from the ALTIBASE HQ.</p></td></tr><tr><th class="confluenceTh"><p>ERR-0001c(errno=76) Unable to shutdown the communication channel</p></th></tr><tr><td class="confluenceTd"><p>During the ALTIBASE shutdown phase, a warning message from the session-related cleanup process has no effect on the operation.</p></td></tr><tr><th class="confluenceTh"><p>ERR-71019 (errno=104) Failed to invoke a system function, write() (read, accept, select)</p></th></tr><tr><td class="confluenceTd"><p>This error occurs by an error in a disk or network. The user must check the file system or make sure there are no network problems. Alternatively, system calls may fail due to insufficient memory.</p></td></tr><tr><th class="confluenceTh"><p>ERR-40029 (errno=16) Failed to invoke a system function, flock_trywrlock()</p></th></tr><tr><td class="confluenceTd"><p>This error occurs when ALTIBASE is already running or ALTIBASE is restarting while it is already running. Or, it can occur when the system call fails due to insufficient memory.</p></td></tr><tr><th class="confluenceTh"><p><span style="color: orange;">ERR-11018 (errno=2) The version of data file for backup is not compatible with the version of storage manager. Backup DB =&gt; [ Version ID = 5.4.1,  Bit = 64, Endian = LITTLE LogSize = 10485760  Transaction Table Size = 1024 ]  Server=&gt;[ Version ID = 5.4.1,  Bit = 64, Endian = LITTLE LogSize = 10485760 Transaction Table Size = 2049 ]</span></p></th></tr><tr><td class="confluenceTd"><p>This error occurs when attempting to recover with a data file that is incompatible with the ALTIBASE version currently in use while running with the backed-up data. Or, this occurs when attempting to run in a different state from the ALTIBASE setting value set at the time of backup.</p></td></tr><tr><th class="confluenceTh"><p>[ERROR] first write () operation failed. errno=32</p></th></tr><tr><td class="confluenceTd"><p>This error occurs in the read/write system call while the session is disconnected, so the information is recorded in the form of a warning. This log is also recorded when an application forces a shutdown without a normal disconnection command. The operation is not affected.</p></td></tr><tr><th class="confluenceTh"><p>ERR-7101d(errno=11) Protocol header error. (TCP 211.115.75.212:63847)<br class="atl-forced-newline" />Protocol processing failed. Close connection...</p></th></tr><tr><td class="confluenceTd"><p>When a session accessed with the ALTIBASE connection port attempts to connect with a version that is not compatible with the ALTIBASE server version, the user must traceback with the output connection information to check whether the server/client versions are compatible. The operation is not affected.</p></td></tr><tr><th class="confluenceTh"><p>ERR-4000f(errno=2) No Error Message Loaded</p></th></tr><tr><td class="confluenceTd"><p>This error occurs when the files located in the $ALTIBASE_HOME/msg/ path do not exist or are not compatible. with the version. Or, this occurs when the user does not have permission to read on the path.</p></td></tr><tr><th class="confluenceTh"><p><span style="color: orange;">[Notify : Query Timeout] Query Canceled by Server : Session ID = 102373</span><br class="atl-forced-newline" /><span style="color: orange;">[Notify : Fetch Timeout] Session Closed by Server : Session ID = 80106</span><br class="atl-forced-newline" /><span style="color: orange;">[Notify : Utrans Timeout] Session Closed by Server : Session ID = 80106</span><br class="atl-forced-newline" /><span style="color: orange;">[Notify : Idle Timeout] Session Closed by Server : Session ID = 80106</span></p></th></tr><tr><td class="confluenceTd"><p>When TIMEOUT occurs due to QUERY/FETCH/UTRANS/IDLE TIMEOUT setting, a warning type log is recorded. If there is a problem, the session information is recorded along with the message, so the user must track the session and resolve it.</p></td></tr><tr><th class="confluenceTh"><p>ERR-01027(errno=0) No more IPC channel (MAX=50, USED=50, BUFSIZE=65536)</p></th></tr><tr><td class="confluenceTd"><p>This error occurs when attempting more IPC access than available resources.</p></td></tr><tr><th class="confluenceTh"><p><span style="color: orange;">[Warning] Memory allocation failed. Size:524320 Timeout: 0</span><br class="atl-forced-newline" /><span style="color: orange;">ERR-61055(errno=12) Memory allocation failure</span></p></th></tr><tr><td class="confluenceTd"><p>This error occurs when an internally required memory allocation fails due to insufficient memory. In this case, the user must determine the cause of insufficient memory and resolve it. If a case of insufficient swap memory occurs, ALTIBASE may terminate abnormally without warning.</p></td></tr><tr><th class="confluenceTh"><p>ioctl() failed</p></th></tr><tr><td class="confluenceTd"><p>This error occurs when there is a temporary problem with performing system calls between socket or disk I/O operations. Generally, this can be ignored, but it is recommended to check the network or disk.</p></td></tr><tr><th class="confluenceTh"><p><span style="color: orange;">WARNING : write error number : 0, file name : /dblog01/logfile537572, file handle : 440, intended size : 10485760, writed size : 10485760</span><br class="atl-forced-newline" /><span style="color: orange;">또는,</span><br class="atl-forced-newline" /><span style="color: orange;">File Extending Failed. : The disk space has been exhausted.</span><br class="atl-forced-newline" /><span style="color: orange;">Error : Extending DataFile : from 0, size 10485760</span></p></th></tr><tr><td class="confluenceTd"><p>When creating a file that ALTIBASE requires due to insufficient disk capacity, this is a warning that the file could not be created normally due to insufficient capacity. The user must check the disk capacity and resolve it.</p></td></tr></tbody></table></div><h3 id="id-3.AltibaseTraceLogs-altibase_sm.log"><strong>altibase_sm.log</strong></h3><hr /><p>altibase.sm.log is an important basis for determining whether checkpoints are being executed and whether there are long-running queries.</p><div class="table-wrap"><table class="confluenceTable"><thead><tr><th class="confluenceTh"><div class="tablesorter-header-inner"><p>[CHECKPOINT-BEGIN]</p></div></th></tr></thead><tbody><tr><td class="confluenceTd"><p>This means the checkpoint has started.</p></td></tr><tr><th class="confluenceTh"><p>Remove Online Log File at LFG [0]: File[220 ~ 227]</p></th></tr><tr><td class="confluenceTd"><p>This message removes the transaction log files that are no longer needed for recovery as the checkpoint is performed. If it is continuously displayed as File [None], it is necessary to check whether there are any queries that have been executed for a long time or that there are no untransmitted parts due to the replication.</p></td></tr><tr><th class="confluenceTh"><p>[CHECKPOINT-summary] BeginChkptLSN=[0,83,9820280], EndChkptLSN=[0,83,9820721], DiskRecLSN=[0,83,9820280]</p></th></tr><tr><td class="confluenceTd"><p>When the checkpoint has been successfully completed, summary information about checkpoint performance information is recorded in the log.</p></td></tr><tr><th class="confluenceTh"><p>[CHECKPOINT-END]</p></th></tr><tr><td class="confluenceTd"><p>This means the checkpoint has been successfully completed.</p></td></tr><tr><th class="confluenceTh"><p>Minimum LSN = [0,83,9824136]</p></th></tr><tr><td class="confluenceTd"><p>The above value is the offset position of the log file being recorded of the transaction in progress. Therefore, if that value does not change and keeps the same value, it is necessary to check whether there is a query that is executed for a long time as in the Remove log above, or whether the replication is not transmitted.</p></td></tr><tr><th class="confluenceTh"><p>Database-Level Backup Completed [SUCCESS]</p></th></tr><tr><td class="confluenceTd"><p>This means the backup has been successfully completed.</p></td></tr><tr><th class="confluenceTh"><p>DISK TABLESPACE .... DATABASE ....</p></th></tr><tr><td class="confluenceTd"><p>This means the backup of disk tablespaces has been performed.</p></td></tr><tr><th class="confluenceTh"><p>~/loganchor0 BACKUP TO</p></th></tr><tr><td class="confluenceTd"><p>This means that the backup of the log anchor has been performed.</p></td></tr><tr><th class="confluenceTh"><p>MEMORY TABLESPACE DATAFILE …. BACKUP TO ….</p></th></tr><tr><td class="confluenceTd"><p>This means that the backup of memory tablespace has been performed.</p></td></tr></tbody></table></div><h3 id="id-3.AltibaseTraceLogs-altibase_qp.log"><strong>altibase_qp.log</strong></h3><hr /><p>In altibase_qp.log, a log of the DDL executed by the user and the case of changing DB property values with “ALTER SYSTEM” statement, etc. are recorded. They are classified as follows.</p><div><p> </p><div class="table-wrap"><table class="confluenceTable"><thead><tr><th class="confluenceTh"><div class="tablesorter-header-inner"><p>[EXEC_DDL_BEGIN : create index T1_IDX on T1 (A)]</p></div></th></tr></thead><tbody><tr><td class="confluenceTd"><p>Log indicating the start of DDL executed by the user</p></td></tr><tr><th class="confluenceTh"><p>[EXEC_DDL_END : SUCCESS]</p></th></tr><tr><td class="confluenceTd"><p>Log indicating the normal completing of DDL executed by the user</p></td></tr><tr><th class="confluenceTh"><p>[EXEC_DDL_END : FAILURE] errorcode 1627549735.</p></th></tr><tr><td class="confluenceTd"><p>Log indicating the error details of DDL executed by the user</p></td></tr><tr><th class="confluenceTh"><p>[SET-PROP] CHECKPOINT_BULK_WRITE_PAGE_COUNT=[0]</p></th></tr><tr><td class="confluenceTd"><p>Log indicating when the user changes the DP property setting value that affects the entire system</p></td></tr></tbody></table></div><h3 id="id-3.AltibaseTraceLogs-altibase_rp.log"><strong>altibase_rp.log</strong></h3><hr /><p>Because altiabse.rp.log records the operation state of replication and queries when various conflicts occur, it provides important tracks for replication problems.</p><div class="table-wrap"><table class="confluenceTable"><thead><tr><th class="confluenceTh"><div class="tablesorter-header-inner"><p>ERR-31017(errno=0) Replication not found</p></div></th></tr></thead><tbody><tr><td class="confluenceTd"><p>This error occurs when the replication target objects do not exist when executing DDL. Therefore, it is necessary to check whether the replication target objects exist.</p></td></tr><tr><th class="confluenceTh"><p>ERR-6200f(errno=16) [Sender] Stop sender thread REP1 at [9765213], Restart SN[9765207]</p></th></tr><tr><td class="confluenceTd"><p>This log is created when the replication sender is explicitly stopped by the user</p></td></tr><tr><th class="confluenceTh"><p>ERR-71017(errno=79) Failed to invoke a system function, connect()<br class="atl-forced-newline" />ERR-61012(errno=79) [Sender] Failed to connect to the peer server<br class="atl-forced-newline" />ERR-61022(errno=79) [Sender] Sender Sleep : 60 seconds<br class="atl-forced-newline" />[Sender] getNextLastUsedHostNo: from 192.168.1.81:53341 to 192.168.1.81:53341<br class="atl-forced-newline" />ERR-61003(errno=9) Unable to read from a socket<br class="atl-forced-newline" />ERR-61012(errno=119) [Sender] Failed to connect to the peer server<br class="atl-forced-newline" />ERR-6100d(errno=119) [Sender] Failed to handshake with the peer server (Handshake Process Error)</p></th></tr><tr><td class="confluenceTd"><p>This is the log when the replication sender cannot connect to the other side's server and attempts to reconnect.</p><p>It is necessary to check whether the other side's server, network status, and ALTIBASE are running properly. If the other party's replication is explicitly dropped, it is a normal error.</p></td></tr><tr><th class="confluenceTh"><p>[Recovery Sender] Replication REP1 Start... at [60495917]</p></th></tr><tr><td class="confluenceTd"><p>This is the log when the replication and the sender have started.</p></td></tr><tr><th class="confluenceTh"><p>[Receiver] Replication REP1 Started ...</p></th></tr><tr><td class="confluenceTd"><p>This is the log when receiver and replication have started properly.</p></td></tr><tr><th class="confluenceTh"><p>RECEIVER:REPLICATION STOP MSG arrived!<br class="atl-forced-newline" />[ReceiverApply] REPLICATION STOP XLog arrived!<br class="atl-forced-newline" />Normal Stop!<br class="atl-forced-newline" />[Receiver] Replication REP1 Stopped ...</p></th></tr><tr><td class="confluenceTd"><p>This is when the replication of other server is explicitly stopped by the user.</p></td></tr><tr><th class="confluenceTh"><p>ERR-61047(errno=0) [Receiver] REP1 receiver has error in recvXlog()<br class="atl-forced-newline" />ERR-61048(errno=0) [Receiver] REP1 receiver has recvXLog error in run()<br class="atl-forced-newline" />ERR-6104b(errno=0) [Receiver] REP1 receiver is ended (by thr_exit)</p></th></tr><tr><td class="confluenceTd"><p>This error occurs when the replication of the other server is explicitly stopped by the user.</p></td></tr><tr><th class="confluenceTh"><p>ERR-61036(errno=0) [Receiver] err_not found in deleteXlog()<br class="atl-forced-newline" />ERR-61000(errno=0) The received record is not found in the database.</p></th></tr><tr><td class="confluenceTd"><p>In the process of executing the DELETE transaction received through replication, if the corresponding record does not exist, this conflict error is recorded.</p></td></tr><tr><th class="confluenceTh"><p>ERR-61035(errno=0) [Receiver] An update conflict encountered.<br class="atl-forced-newline" />ERR-61001(errno=0) A conflict has been occurred while executing the received statement.</p></th></tr><tr><td class="confluenceTd"><p>This error occurs when a conflict error is recorded because the before/after values of the corresponding record are different during the process of executing the UPDATE transaction received through replication.</p></td></tr><tr><th class="confluenceTh"><p>ERR-6103a(errno=0) [Receiver] err_not_found in updateXlog()<br class="atl-forced-newline" />ERR-61000(errno=0) The received record is not found in the database.</p></th></tr><tr><td class="confluenceTd"><p>In the process of executing the UPDATE transaction received replication, if the corresponding record does not exist, this conflict error is recorded.</p></td></tr><tr><th class="confluenceTh"><p>ERR-11058(errno=0) The row already exists in a unique index.</p></th></tr><tr><td class="confluenceTd"><p>In the process of executing the INSERT received through replication, the corresponding record already exists on the receiving side. (There are data with the same PK)</p></td></tr></tbody></table></div><p>The name of the replication object used in the example above is “REP1”. Since the name of the replication object specified by the user will be different, it should be considered when searching for errors, and it is recommended to detect the operation state of the replication Sender/Receiver and conflict errors.</p><p>In addition, if a conflict occurs, it is important to find the cause of the conflict with the SQL statement that remains when the conflict occurs, because there is a possibility that data inconsistency may have occurred due to either not properly complying with the considerations of the replication environment described above.</p><h3 id="id-3.AltibaseTraceLogs-altibase_dk.log"><strong>altibase_dk.log</strong></h3><hr /><p>In altibase_dk.log, various information and errors that may occur in the environment using the Database Link are recorded.</p><div class="table-wrap"><table class="confluenceTable"><thead><tr><th class="confluenceTh"><div class="tablesorter-header-inner"><p>ERR-b1070(errno=0) ODBC problem occurred [0:IM002:[unixODBC][Driver Manager]Data source name not found, and no default driver specified]</p></div></th></tr></thead><tbody><tr><td class="confluenceTd"><p>This error occurs when the specified data source name is not found or LD_LIBRARY_PATH is not set.</p></td></tr><tr><th class="confluenceTh"><p>ERR-b1070(errno=239) ODBC problem occurred [327730:08001:Client unable to establish connection.]</p></th></tr><tr><td class="confluenceTd"><p>This error occurs when it is not possible to connect to the Altibase server or when the odbc.ini environment variable is not set. This can be resolved by checking the server running state and adding odbc.ini to the environment variable.</p></td></tr></tbody></table></div><h3 id="id-3.AltibaseTraceLogs-altibase_error.log"><strong>altibase_error.log</strong></h3><hr />The altibase_error.log provides tracks for analyzing the cause of abnormal termination of ALTIBASE.<div class="table-wrap"><table class="confluenceTable"><thead><tr><th class="confluenceTh"><div class="tablesorter-header-inner"><p><span style="color: orange;">BEGIN-STACK-[CRASH]=====================================</span><br class="atl-forced-newline" /><span style="color: orange;">END-STACK=====================================</span><br class="atl-forced-newline" /><span style="color: orange;"> [========= FATAL Terminated ==========]</span></p></div></th></tr></thead><tbody><tr><td class="confluenceTd"><p>When ALTIBASE is abnormally terminated due to a bug, its own trace log is outputted in which process occurred. If this error occurs, the ALTIBASE process is terminated. First, backup all files in $ALTIBASE_HOME/trc/. Then backup the redo log files and, if there is enough disk space, even get the database file. When such file backup is completed, resolve it by restarting ALTIBASE and contact ALTIBASE for technical support.</p></td></tr></tbody></table></div></div>
                    </div>

                    
                                                      
                </div>             </div> 
            <div id="footer" role="contentinfo">
                <section class="footer-body">
                    <p>Document generated by Confluence on Jun 23, 2021 09:49</p>
                    <div id="footer-logo"><a href="http://www.atlassian.com/">Atlassian</a></div>
                </section>
            </div>
        </div>     </body>
</html>
